name: CI
on: [push]

jobs:
    build:
      name: Run Script
      runs-on: ubuntu-latest
      steps:
        - uses: action/checkout@v1
        - name: Script
          run: ./Github-Create-Repository.ps1
          shell: pwsh
