name: CI - Powershell Script
on: [push]

jobs:
    build:
      name: Run Script
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Script
          run: ./Github-Create-Repository.ps1
          shell: pwsh
