name: CI - Powershell Script
on: [push]

jobs:
    build:
      name: Run Script
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Script
          run: PowerShell-Script/Github-Create-Repository.ps1
          shell: pwsh
